version: '3.9'

services:
  api:
    container_name: dvdapi
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}

    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis:7.0-alpine
    restart: on-failure
    ports:
      - '6379:6379'
